on: [push, pull_request]
name: Go
jobs:
  test:
    name: Test Go latest two versions
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download dependencies
      run: go mod download

    - name: Go Vet
      run: go vet ./...

    - name: Test 
      run: go test -v ./...
